-- 0023 — Account nicknames (display names)
--
-- Any account may choose a nickname: it is how participants recognise each other
-- instead of reading out a public ID. The public ID stays the identifier of record
-- and is still shown next to the nickname, so a lookalike name cannot silently
-- impersonate somebody.
--
-- Additive: display_name is nullable, so every existing account keeps working with
-- no nickname at all.

alter table public.account add column if not exists display_name text;

-- The uniqueness key is GENERATED, not written by the app: a key the application
-- computes can drift from the name it was derived from, and then two accounts can
-- hold what readers see as the same nickname. Postgres keeps them in lockstep.
alter table public.account
  add column if not exists display_name_key text
  generated always as (lower(btrim(display_name))) stored;

-- NULLs are distinct in a Postgres unique index, so any number of accounts can have
-- no nickname; only actual names must be unique.
create unique index if not exists account_display_name_key_uniq
  on public.account (display_name_key);

alter table public.account drop constraint if exists account_display_name_len;
alter table public.account add constraint account_display_name_len
  check (display_name is null or char_length(btrim(display_name)) between 2 and 24);

comment on column public.account.display_name is
  'Optional participant-chosen nickname. Shown WITH the public ID, never instead of it.';
comment on column public.account.display_name_key is
  'Case-folded uniqueness key, generated by Postgres so it cannot drift from display_name.';
